### ISSUE TITLE
boolean

### ISSUE THREAD

**Issue by ENDER1355** [VeggieStick/veggie-ss-tool#1]

**Comment by ENDER1355** [comment]
if you ask why i am here, none of your business

**Comment by ENDER1355** [comment]
whatever, I use Liquidbounce's API to make my scripts, also it's a script. also if u try out my old PVP land script, you would get banned obviously.

**Comment by ENDER1355** [comment]
@VeggieStick also if u know coding so much, then code your own disabler.

**Comment by ENDER1355** [comment]
https://github.com/ENDER1355/pvp-land-disabler-dev/blob/main/disabler.js

**Comment by VeggieStick** [comment]
You clearly dont know anything. You claim to code disablers and shit but literally EVERYTHING on your github is forked. You also couldn't answer what a boolean is.
![ender1](https://user-images.githubusercontent.com/87394020/126923233-b75a2831-67e8-49f0-8455-250b9c8886b2.png)

**Comment by VeggieStick** [comment]
> 
> 
> literally all of the fakemen staff codes in batch, and uuid tried to hide the fact that he does it too

uuid literally knows nothing in batch and codes in java

**Comment by VeggieStick** [comment]
> 
> 
> hey also can u try out mp3's regedit?
> 
> https://www.youtube.com/watch?v=MyCmnyXvnHw

not sure what ur trying to say here, it works fine

**Comment by VeggieStick** [comment]
> 
> 
> > literally EVERYTHING on your github is forked
> 
> thats called a pull request
> 
> also if u know coding so much, tell me how to find square root of 4 and divide it to 2 in java

they arent pull requests they are literally forks
